services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    mm_shop_bundle:
        class: 'Bits\MmShopBundle\MmShopBundle'
        public: true
    
        
    Bits\MmShopBundle\Migration\InstallMmShop:
        arguments:
            $connection: '@database_connection'
        tags:
            - { name: contao.migration }
            
    Bits\MmShopBundle\EventListener\Product\DefaultValueCartCount:
        public: true
        tags:
            - { name: kernel.event_listener, event: dc-general.factory.build-data-definition }
            
    Contao\CoreBundle\Security\Csrf\ContaoCsrfTokenManager:
        public: true
    
    security.csrf.token_manager:
        class: Symfony\Component\Security\Csrf\CsrfTokenManager
        public: true
        
    Bits\MmShopBundle\:
        resource: '../src/*'
        exclude: '../src/{Resources,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

   
