parameters: null

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    mm_shop_bundle:
        class: 'Bits\MmShopBundle\MmShopBundle'
        public: true
    
        
    Bits\MmShopBundle\Migration\InstallMmShop:
        arguments:
            $connection: '@database_connection'
        tags:
            - { name: contao.migration }
            
    Bits\MmShopBundle\EventListener\Asset\AddAssetListener:
        arguments:
            $scopeMatcher: '@contao.routing.scope_matcher'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 1 }
    
    Bits\MmShopBundle\Controller\ProductListController:
        autoconfigure: false
        tags: ['controller.service_arguments']
        
    Bits\MmShopBundle\Controller\ProductDetailController:
        autoconfigure: false
        tags: ['controller.service_arguments']
    
    
    Bits\MmShopBundle\Service\ResourceResolver: ~
    
    Bits\MmShopBundle\Routing\DynamicRouteLoader:
        autoconfigure: false
        arguments:
            $resourceResolver: '@Bits\MmShopBundle\Service\ResourceResolver'
            $db: '@doctrine.dbal.default_connection'
        tags:
            - { name: routing.loader }
            
    Contao\CoreBundle\Security\Csrf\ContaoCsrfTokenManager:
        public: true
    
    security.csrf.token_manager:
        class: Symfony\Component\Security\Csrf\CsrfTokenManager
        public: true
        
    Bits\MmShopBundle\:
        resource: '../src/*'
        exclude: '../src/{Controller,Resources,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

